### ISSUE TITLE
[Add] Add convention.md and templates.md

### ISSUE THREAD

**Issue by dtd1232** [kiyounkim/23-2Project#9]
### 📝 작업 목적

협업을 위한 컨벤션과 이슈, PR 템플릿을 추가하기 위함.

---

### 🛠️ Tasks

* [ ] convention.md 추가
* [ ] template 추가
  * [ ] .github 폴더 생성
  * [ ] ISSUE_TEMPLATE.md, PULL_REQUEST_TEMPLATE.md 추가
